global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:9000"]

  - job_name: "triton"
    metrics_path: /metrics
    static_configs:
      - targets: ["triton:8002"]
